/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : CLD
 #	author : miyako
 #	2016/04/19
 #
 # --------------------------------------------------------------------------------*/

#include "encodings/compact_lang_det/compact_lang_det.h"
#include "encodings/compact_lang_det/ext_lang_enc.h"
#include "encodings/compact_lang_det/unittest_data.h"
#include "encodings/proto/encodings.pb.h"

// --- CLD
void CLD_Detect_language(sLONG_PTR *pResult, PackagePtr pParams);
